blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://discourse.joplinapp.org/t/secure-notes/47501
    about: General questions, usage help, and discussion happen on the Joplin Forum.
